services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27018:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=timaslilaila
      - MONGO_INITDB_ROOT_PASSWORD=7RiZRnQZYmJOKt7u

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=timaslilaila
      - ME_CONFIG_MONGODB_ADMINPASSWORD=7RiZRnQZYmJOKt7u
      - ME_CONFIG_MONGODB_SERVER=mongodb

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: